services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-site
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./site:/var/www/html/site
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-site
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh

  

